### ISSUE TITLE
Invalid file path

### ISSUE THREAD

**Issue by jdziat** [NickNaso/ghostscript4js#16]
When building on windows i found that the file:
g4js-home.js
should be named
gs4js-env-home.js

see the binding file snippet below:
` ['OS=="win"', {
          "conditions": [
            ['target_arch=="x64"', {
              "variables": {
                "GS4JS_HOME%": "<!(node gs4js-env-home.js)",  
                "GS4JS_LIB%": "gsdll64.lib",
                "GS4JS_DLL%": "gsdll64.dll",
                "conditions": [
                  ['"<!(node gs4js-env-home.js)" == ""', {
                    "GS4JS_HOME%": "C:/gs/bin"
                  }]
                ]
              }
            }, 
            {
              "variables": { 
                "GS4JS_HOME%": "<!(node gs4js-env-home.js)",  
                "GS4JS_LIB%": "gsdll32.lib",
                "GS4JS_DLL%": "gsdll32.dll",
                "conditions": [
                  ['"<!(node gs4js-env-home.js)" == ""', {
                    "GS4JS_HOME%": "C:/gs/bin"
                  }]
                ]
              }
            }]
          ],`

**Comment by NickNaso** [comment]
Hi @jdziat,
thank you for your report. Now the installation work fine also on windows. I changed the name of the script that retrieve the environment variable in windows system. All is published on npm with version 1.0.19.
