### ISSUE TITLE
Issue with the new update ghostscript4js@2.0.5

### ISSUE THREAD

**Issue by dvoch** [NickNaso/ghostscript4js#24]
Hi, I tried to run npm update today and when running the update of ghostscript4js I have this issue:

Error: Cannot find module 'C:\Tools\EB\back\node_modules\ghostscript4js\gs4js-env-dll.js'
...
gyp: Call to 'node gs4js-env-dll.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp

Anyone encountered this issue?
Thanks for any helps!
Regards
D.

I posted before on the ghostscriptjs issue forum and thanks rmeja to remind me! Sorry for that

**Comment by NickNaso** [comment]
Hi @dvoch ,
I just provided to solve the problem. Unfortunately I forgot to update the ```files``` section on **package.json** file. Now the problem has been fixed and I published the new release 2.0.7.
Please try the new version end in case you continue to experiment some troubles don't hesitate to contact us.
