### ISSUE TITLE
-dNOPAUSE not working

### ISSUE THREAD

**Issue by GuiJordao21** [NickNaso/ghostscript4js#43]
Even if i pass this flag, my program still waits for the <return> key to be pressed. Did someone have the same problem?

**Comment by NickNaso** [comment]
Hi @GuiJordao21 ,
could you report which version of Node.js and Ghostscript you are using?

**Comment by GuiJordao21** [comment]
GPL Ghostscript 9.26 (2018-11-20)
node -v 10.15.3

I used the sample code on documentation. when I run the same cmd on bash, everything works fine.

**Comment by NickNaso** [comment]
@GuiJordao21 could you try to execute the following code? 

```js
'use strict'

const gs = require('ghostscript4js')

async function run() {
     // Take decision based on Ghostscript version
     const version = gs.version()
     console.log(version)
     await gs.execute('-psconv -q -dNOPAUSE -sDEVICE=pngalpha -o my.png -sDEVICE=pngalpha -r144 my.pdf')
}

run().catch( err => { console.error(err) })
```

**Comment by GuiJordao21** [comment]
Sorry for the delay.

This worked fine, but some pictures are diferente of what I was expecting and I think is because of pngalpha. Don't really know the diference between this one and png16m though.

But why this worked and the other code snippet doesn't?
