### ISSUE TITLE
Segmentation fault on multiple runs

### ISSUE THREAD

**Issue by hamzashezad** [NickNaso/ghostscript4js#47]
OS: macOS 10.14.5
Node version: 10.15.3
Ghostscript version: 9.27 (2019-04-04)
Electron version: 5.0.7
Ghostscript4js version: 3.1.1

I am converting postscript files to text files using the following: 

```js
gs.executeSync("-sDEVICE=txtwrite -dNOPAUSE -dQUIET -dBATCH \
    -sOutputFile=output.txt -sDEVICE=txtwrite input.ps");
```

It works the first time but my electron application crashes when I try to convert a second file.

The command runs fine on bash but gives a segmentation fault when I run it on Node REPL:

```js
> const gs = require("ghostscript4js")
undefined
> gs.executeSync("-sDEVICE=txtwrite -dNOPAUSE -dQUIET -dBATCH -sOutputFile=job1.txt -sDEVICE=txtwrite job-1.ps")
undefined
> gs.executeSync("-sDEVICE=txtwrite -dNOPAUSE -dQUIET -dBATCH -sOutputFile=job2.txt -sDEVICE=txtwrite job-1.ps")
[1]    70491 segmentation fault  node
```

Note `job2.txt` was not created and it crashed after with a segmentation fault.

**Comment by BoxSo** [comment]
I see this happening on windows 10 with ghostscript 9.27 too. First run works like a charm, second run crashes app without any feedback.

**Comment by GautierT** [comment]
Same problem. first run is okay second run crash the app without any feedback.
`Ghostscript.version()` :
```
{
  product: 'GPL Ghostscript',
  copyright: 'Copyright (C) 2019 Artifex Software, Inc.  All rights reserved.',
  revision: 950,
  revisiondate: 20191015
}
```

**Comment by MySendingBox** [comment]
Hi @NickNaso 
Do you have an idea how to fix this ? Or how to downgrade to 9.22 on macos (installed from brew) ?
I have only one version in `/usr/local/Cellar/ghostscript/` and it's 9.50.

Thanks !

**Comment by GautierT** [comment]
Hi @NickNaso
Do you have an idea how to fix this ? Or how to downgrade to 9.22 on macos (installed from brew) ?
I have only one version in /usr/local/Cellar/ghostscript/ and it's 9.50.

Thanks !

**Comment by luco** [comment]
+1 on this on mac. On the second run it gives me 
`[1]    89399 segmentation fault  node --inspect index.js`

@NickNaso thoughts?

**Comment by NickNaso** [comment]
Hi everybody,
I'm closing the issue because the release `3.2.0` should solve the problem.
