### ISSUE TITLE
Ghostscript version from homebrew is too new

### ISSUE THREAD

**Issue by bbqaaq** [NickNaso/ghostscript4js#48]
Close

**Comment by bbqaaq** [comment]
Please close this issue, I have made something wrong

**Comment by NickNaso** [comment]
Hi @bbqaaq,

If you install `ghostscript` through **homebrew** the entire solution is in this following folder:
`/usr/local/Cellar/ghostscript/{VERSION}/` the most simple thing to do is to create a symbolic link in `/usr/local/lib` that point to  `/usr/local/Cellar/ghostscript/{VERSION}/lib/libgs.dylib`.
Hope that this will help you.

**Comment by NickNaso** [comment]
Ok I provide to close feel free to open new issue if you need other help.

**Comment by bbqaaq** [comment]
@NickNaso Sorry that I have made sth wrong.
Turn out the problem can be solved by reinstalling the package.

But I found that another issue #47 happens on my side too, as Im using 9.27 also.
See if that issue is related to gs 9.27 with ghostscript4js.

Thanks!
