### ISSUE TITLE
execution stop with: double free or corruption (fasttop)

### ISSUE THREAD

**Issue by daton89** [NickNaso/ghostscript4js#49]
Hi nick,

I try to run the execute with tiffsep and sometimes it works and sometimes I get an error: `double free or corruption (fasttop)`

```js
const gs = require('ghostscript4js')

;(async function() {

await gs.execute(`-dBATCH -dNOPAUSE -dSAFER -sDEVICE=tiffsep -dFirstPage=1 -dLastPage=1 -r265 -sOutputFile=output.tif input.pdf`)
})()
```

Unfortunately when this happens the package only shows the error in the console but I'm not able to intercept it in a try-catch. 

I'm running Node 8.16.2 on Fedora 31 
GPL Ghostscript 9.27 (2019-04-04)
"ghostscript4js": "^3.1.1",

**Comment by NickNaso** [comment]
Hi everybody,
I'm closing the issue because the release `3.2.0` should solve the problem.
